# Generated by Django 2.2.4 on 2019-08-15 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone')),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='O título deverá ter no máximo 100 caractéres', max_length=100, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('data_publicacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Autor')),
            ],
        ),
    ]
